config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'

  resources :cities
  resources :events
  resources :topics
  resources :user_filters

  root 'welcome#index'
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :events_topics, dependent: :destroy
  has_many :events, through: :events_topics

  def to_s
    name
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:name)
    end
end

app/views/topics/_form.html.slim
= form_for(topic) do |f|
  - if topic.errors.any?
    #error_explanation
      h2
        = pluralize(topic.errors.count, "error")
        |  prohibited this topic from being saved:
      ul
        - topic.errors.full_messages.each do |message|
          li
            = message
  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit

app/views/topics/edit.html.slim
h1
  | Editing Topic
= render 'form', topic: @topic
= link_to 'Show', @topic
|  | 
= link_to 'Back', topics_path

app/views/topics/index.html.slim
p#notice
  = notice
h1
  | Topics
table
  thead
    tr
      th
        | Name
      th[colspan="3"]
  tbody
    - @topics.each do |topic|
      tr
        td
          = topic.name
        td
          = link_to 'Show', topic
        td
          = link_to 'Edit', edit_topic_path(topic)
        td
          = link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' }
br
= link_to 'New Topic', new_topic_path

app/views/topics/new.html.slim
h1
  | New Topic
= render 'form', topic: @topic
= link_to 'Back', topics_path

app/views/topics/show.html.slim
p#notice
  = notice
p
  strong
    | Name:
  = @topic.name
= link_to 'Edit', edit_topic_path(@topic)
|  | 
= link_to 'Back', topics_path