config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'

  resources :cities
  resources :events
  resources :topics
  resources :user_filters

  root 'welcome#index'
end

app/views/shared/_navbar.html.slim
nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      button.navbar-toggle.collapsed[type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false"]
        span.sr-only
          | Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to "Logo", root_path, class: "navbar-brand"
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      ul.nav.navbar-nav.navbar-right
        - if current_user
          = render partial: 'shared/notification_feed'
          li
            = link_to "Sign Out", destroy_user_session_path, method: "delete"
        - else
          li
            = link_to "Sign Up", new_user_registration_path
          li
            = link_to "Sign In", new_user_session_path

app/views/shared/_notification_feed.html.slim
li.dropdown.dropdown-notifications
  a.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button"
    span Уведомления
    span.badge.count-notifications #{@notifications.count}
    span.caret
  ul.dropdown-menu.notifications
    - @notifications.each do |j|
      = render partial: 'shared/notification_item', locals: { event: j.event }

app/views/shared/_notification_item.html.slim
li
  = link_to event, event_path(event)