config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'

  resources :cities
  resources :events
  resources :topics
  resources :user_filters

  root 'welcome#index'
end

app/models/event.rb
class Event < ApplicationRecord
  include Observers::EventObserver

  belongs_to :city
  has_many :events_topics, dependent: :destroy
  has_many :topics, through: :events_topics

  scope :by_city, ->(city_id) { where(city_id: city_id) }
  scope :by_topic, ->(topic_id) { joins(:events_topics).where(events_topics: { topic_id: topic_id } ) }

  def to_s
    name
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include EventFilters

  before_action :set_event, only: [:show, :edit, :update, :destroy]

  has_scope :by_city, only: [:index]
  has_scope :by_topic, only: [:index]

  # GET /events
  # GET /events.json
  def index
    @events = apply_scopes(Event).search(params[:q]).result.page(params[:page])
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :city_id, :start_date, :end_date, :location)
    end
end

app/views/events/_filter.html.slim
= form_tag(events_path, method: :get) do
  = label_tag :by_city, 'Город'
  = select_tag :by_city, options_from_collection_for_select(City.all, 'id', 'name', params[:by_city]), class: 'form-control', prompt: 'Выберите'
  = label_tag :by_topic, 'Тема'
  = select_tag :by_topic, options_from_collection_for_select(Topic.all, 'id', 'name', params[:by_topic]), class: 'form-control', prompt: 'Выберите'
  .row
    .col-sm-6
      = label_tag :'q[start_date_gteq]', 'Начало периода'
      = search_field_tag :'q[start_date_gteq]', params[:q].try(:[], :start_date_gteq), class: 'datetimepicker form-control', id: 'fromDate'
    .col-sm-6
      = label_tag :'q[start_date_lteq]', 'Конец периода'
      = search_field_tag :'q[start_date_lteq]', params[:q].try(:[], :start_date_lteq), class: 'datetimepicker form-control', id: 'toDate'
  .field
    = check_box_tag :remember_filter
    = label_tag :remember_filter, 'Запомнить фильтр'
  - if current_user.user_filter.present?
    .field
      = check_box_tag :restore_filter
      = label_tag :restore_filter, 'Использовать сохраненный фильтр'
  = submit_tag 'Поиск', class: 'btn btn-primary'
  = link_to 'Все события', events_path, class: 'btn btn-primary'

app/views/events/_form.html.slim
= form_for(event) do |f|
  - if event.errors.any?
    #error_explanation
      h2
        = pluralize(event.errors.count, "error")
        |  prohibited this event from being saved:
      ul
        - event.errors.full_messages.each do |message|
          li
            = message
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :city_id
    = f.number_field :city_id
  .row
    .col-sm-6
      = f.label :start_date
      = f.text_field :start_date, class: 'datetimepicker form-control'
    .col-sm-6
      = f.label :end_date
      = f.text_field :end_date, class: 'datetimepicker form-control'
  .field
    = f.label :location
    = f.text_field :location
  .actions
    = f.submit

app/views/events/edit.html.slim
h1
  | Editing Event
= render 'form', event: @event
= link_to 'Show', @event
|  | 
= link_to 'Back', events_path

app/views/events/index.html.slim
p#notice
  = notice
h1
  | События

.row
  .col-md-3
    = render partial: 'filter'

  .col-md-9
    table.table.table-bordered
      thead
        tr
          th
            | Название
          th
            | Город
          th
            | Дата начала
          th
            | Дата окончания
          th
            | Место проведения
          th
      tfoot
        - if @events.empty?
          | Нет записей
        = paginate @events
      tbody
        - @events.each do |event|
          tr
            td
              = event.name
            td
              = event.city
            td
              = event.start_date
            td
              = event.end_date
            td
              = event.location
            td
              = link_to 'Посмотреть', event

app/views/events/new.html.slim
h1
  | New Event
= render 'form', event: @event
= link_to 'Back', events_path

app/views/events/show.html.slim
p#notice
  = notice
p
  strong
    | Name:
  = @event.name
p
  strong
    | City:
  = @event.city
p
  strong
    | Start date:
  = @event.start_date
p
  strong
    | End date:
  = @event.end_date
p
  strong
    | Location:
  = @event.location
= link_to 'Edit', edit_event_path(@event)
|  | 
= link_to 'Back', events_path